// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchWord() {
  return window['go']['main']['App']['FetchWord']();
}

export function GetData() {
  return window['go']['main']['App']['GetData']();
}

export function SaveResult(arg1, arg2) {
  return window['go']['main']['App']['SaveResult'](arg1, arg2);
}
